spring:
  application:
    name: wanguo
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/wanguo_db
    url: jdbc:mysql://mysql8/wanguo_db
    username: root
    password: ohjohj
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: 120.79.233.213
    database: 0
  # 设置登陆的用户名和密码
  security:
    user:
      name: HipopAndLzh
      password: LzhAndHipop

server:
  port: 8080
  servlet:
    context-path: /wanguo
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)